<!-- To create a newsletter blog post on the site do either of the following set of steps: -->

\
<!-- A. Simple -->\
<!-- 1. Copy this text to a raw text editor -->\
<!-- 2. Replace or remove all of the < > sections where appropriate -->\
<!-- 3. Delete these instructions -->\
<!-- 4. Send a copy of this to another member who can upload it -->

<!-- B. Complete -->

\
<!-- 1. Create a new folder in the posts folder with the format YYYY-MM-DD-newsletter-very-brief-description -->\
<!-- 2. Copy this newsletter.qmd file into the folder you created and rename it to index.qmd-->\
<!-- 3. Replace or remove all of the < > sections where appropriate -->\
<!-- 4. Delete these instructions -->\
<!-- 5. Click Render and push to GitHub -->

---
title: "<Month> Newsletter | <3-4 word summary of next workshop>"
editor: visual
author: '<your name here>'
date: "<YYYY-MM-DD>"
image: <thumbnail image for post, delete if no image>
slug: newsletter-<Mmmyyyy>
categories:
  - newsletter
tags: []
DisableComments: no
---

## Geospatial Community June Newsletter

### Drop-in virtual help session this Thursday (June 1st, 3-5 pm)

Drop-in sessions are back this Thursday, so bring your thorniest spatial questions and we'll help problem solve. The first half of the session [Dr Jackson Stockbridge](https://experts.griffith.edu.au/40748-jackson-stockbridge) will give a brief overview of how to access web mapping services (WMS) and web feature services (WFS) in R.

### Next workshop -- June 15th, 2-4pm

Join us for an exciting session where [Dr César Herrara Acosta](https://experts.griffith.edu.au/30877-c%C3%A9sar-herrera-acosta) (Griffith University) will take you on a new dive into the dynamic world of the Python programming language ecosystem! Building upon previous sessions, César will showcase Python libraries for (1) analysis and visualization of spatial data (e.g. geopandas, datashader, holoviews) and (2) basic computer vision algorithms (OpenCV). César will also make use of the incredibly versatile Jupyter Notebooks and Jupyter Lab frameworks, which empowers users with seamless workflows for code development, data exploration, and interactive presentations.

### Previous workshop

Last month, Dr Tony Howes (UQ, School of Chemical Engineering) ran an excellent workshop on how to make an interactive map using Python and Folium. 

## Geospatial Community Updates

<Optional Section about our community>

-   Group changes
-   website updates
-   surveys
-   ideas for upcoming workshops
-   testimonials
-   org committee details
-   Anything about us that we might want to share

## Geospatial News

<Optional section covering broader geospatial news>

-   Conferences/Forums/Resbaz
-   New software/packages
-   Podcasts/Media
-   New useful resources

## Geospatial Jobs

<Optional section listing geospatial job vacancies>

-   Government Jobs
-   Industry Jobs
-   Not for profit/NGO Jobs
-   University Jobs

## Training

<Optional section on GeoSpatial training opportunities>

-   Upcoming UQ Library Training
-   University/School specific training
-   Other training opportunities
