---
metadata-files:
  - _metadata.yml
---

```{=html}
<style>

body {
    font-size: 1em;
}
.fixed-top {
  display: none;
}
#top-right quarto-color-scheme-toggle {
display: none;
}

.tui-view-7 {
height: 100% !important;
}
.tui-full-calendar-month {
    height: 75%;
    min-height: 500px;
}
.tui-full-calendar-popup-detail .tui-full-calendar-popup-container {
    width: 330px;
}
.card-img{
  width: 100px;
}
img {
    width: 100px;
    height: 100% !important;
    max-height: 100px !important;
}

.column-margin.column-container>*:not(.collapse) {
    padding-top: 14em;
}

@media (max-width: 767.98px){
  #events-calendar{
    display: none;
  }
}
</style>
```
```{r calendar, message=FALSE}
#| include: false

library(googlesheets4)
#gs4_auth(cache = ".secrets", email = "itsuqnick@gmail.com")
gs4_deauth()
cal_data <- read_sheet("https://docs.google.com/spreadsheets/d/1HHxs4SsFO1ImH5XbMgTwK2QrheN8d8N3_9P5L0QiPUg/edit#gid=308321545", sheet = "confirmed")
cal_prop <- read_sheet("https://docs.google.com/spreadsheets/d/1HHxs4SsFO1ImH5XbMgTwK2QrheN8d8N3_9P5L0QiPUg/edit#gid=308321545", sheet = "cal_properties")

#install.packages("toastui")
library(toastui)
```

```{r message=FALSE, warning=FALSE}
#| echo: false
#| warning: false
#| error: false


calendar(cal_data, navigation = TRUE, defaultDate = Sys.Date(), height = "600", view = "month") %>% 
  cal_month_options(
    startDayOfWeek  = 1, 
    workweek = TRUE
  ) %>% 
  cal_props(cal_prop)
```
